# docker-compose.yml
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30

  streamlit-app:
    build: ./streamlit-app
    container_name: streamlit-app
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      # sesuaikan MODEL_NAME & DIMS dgn model yang Anda pakai saat buat embedding
      - MODEL_NAME=sentence-transformers/all-MiniLM-L6-v2
      - VECTOR_DIMS=384
      - ES_HOST=http://elasticsearch:9200
      - ES_INDEX=docs
    volumes:
      - ./streamlit-app:/app
      - ./data:/data
    ports:
      - "8501:8501"
